import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./global/storeProvider";
import Header from "./components/Header";
import MainEntry from "./components/MainEntry";
import { ThemeProvider } from "./components/Theming";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <body className={inter.className}>
            {/* <MainEntry children={children} /> */}
            <Header />
            {children}
          </body>
        </ThemeProvider>
      </html>
    </StoreProvider>
  );
}
